spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/groupware
    username: groupware
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
